{% set name = "vizdet" %}
{% set version = "0.1.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/vizdet-{{ version }}.tar.gz
  sha256: c5c6df978dd3417a9f738d382ea6a20bea8dbad7cdec3be2a26b38c0d34658b7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - numpy >=1.20.3
    - python >=3.7
    - libopencv >=4.5.1
    - opencv >=4.5.1
    - py-opencv >=4.5.1

test:
  imports:
    - vizdet
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tadejsv/vizdet
  doc_url: https://vizdet.readthedocs.io
  dev_url: https://github.com/tadejsv/vizdet
  summary: Vizualization for Detection and Tracking
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tadejsv
